### ISSUE TITLE
can't travis login

### ISSUE THREAD

**Issue by jp1017** [nukc/how-to-use-travis-ci#1]
travis 登录出现了问题：
https://github.com/travis-ci/travis.rb/issues/390

**Comment by nukc** [comment]
很抱歉，我没有遇到过这个问题，所以我也不知道怎么去解决。
对于这个问题我只能去猜测会不会是GFW导致的，或者你可以试试

``` ruby
travis login --org
```

``` ruby
travis login --github-token
```

``` ruby
travis login --auto
```

如果你解决了这个问题，希望你能分享下怎么解决。

**Comment by jp1017** [comment]
@nukc 解决了。
是windows的问题，win10自带bash，在bash下部署成功了。

**Comment by nukc** [comment]
@jp1017 好的，谢谢你的分享。
