### ISSUE TITLE
failed to find Build Tools revision 24.0.0

### ISSUE THREAD

**Issue by xingstarx** [nukc/how-to-use-travis-ci#2]
I first use travis-ci

my repo is [MergeAdapter](https://github.com/xingstarx/MergeAdapter)

this is my travis.yml content , https://github.com/xingstarx/MergeAdapter/blob/master/.travis.yml

can you help me , why pull request check get failed to find Build Tools revision 24.0.0

```
The command "./gradlew assembleRelease" failed. Retrying, 2 of 3.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> failed to find Build Tools revision 24.0.0
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by nukc** [comment]
Maybe you should use `- build-tools-24.0.0` .

**Comment by xingstarx** [comment]
Thanks ,  I modified app/build.gradle file , 
-    buildToolsVersion "24.0.0"
-    buildToolsVersion "23.0.3"

and The Travis CI build passed

I will test - build-tools-24.0.0 .in future 

(跟国人说英文额，有点不习惯额，多谢了)

**Comment by nukc** [comment]
:) 能帮到你就好。
